### PR TITLE
Reorganization

### LINKED ISSUE #18: Reorganization and name change
I'm currently using this script to build FlyEM's package stack, and I'd like to start recommending it to others when appropriate.  What do you think of the following proposal:

- Reorganize the files into a proper python package with `setup.py`, `entry_points`, a conda recipe, docs, etc.  Heck, maybe even some tests...
- Remove project-specific configuration files like `ilastik-recipe-specs.yaml`, etc.
- Rename the package to something more generic.  Any opinions here?  Maybe something like, I don't know, `build-recipes`, or `publish-recipes`, or `publish-stack`, etc.

### PR DESCRIPTION
**Pull request by k-dominik**
work in progress.

**Current summary**:

* added ci integration with travis
* added conda recipe
* moved main file to package
* added `setup.py` with proper entry-point
* versioning with `bumpversion`
* uploaded `v0.2.0dev1` to `ilastik-forge`
  ```
  conda install -c ilastik-forge -c conda-forge publish-conda-stack
  ```
* example invocation (after install):
  ```bash
  publish-conda-stack ilastik-recipe-specs
  ```

**Todos**:
- [x] add `activate` script for `argcomplete` (thx for the hint @stuarteberg )
- [x] update `README`
- [x] remove, move example recipes, pins -> proposed name `ilastik/ilastik-conda-recipes`, or `ilastik-feedstocks`?

Dropped, issues opened:
- add method to generat a "blank" config for new users
- add tests and examples

closes #18

### CODE REVIEW

**Comment by stuarteberg** [comment]
Nice! Looks good to me so far.

> add `post-link`, (`pre-unlink` script?) for `argcomplete`

Ah, good idea, I didn't even think of this.  But I think it might be better to write a script for `${PREFIX}/etc/conda/activate.d/`, rather than write a `post-link.sh` script.

**Comment by stuarteberg** [comment]
@k-dominik Just FYI -- I pushed three tiny commits to your branch, so please don't force-push to it without pulling first :-)

**Comment by k-dominik** [comment]
:) cheers! Hightly appreciated. I should probably wrap this one up - it's in a useful enough state...

**Comment by stuarteberg** [comment]
>I should probably wrap this one up - it's in a useful enough state...

I agree, it's quite usable already.  Regarding the "to-do" items above:

> - [ ] tests
> - [ ] add method to generat a "blank" config for new users

More examples/tests/docs would be nice, but should not delay merging of this PR, IMHO.

> - [ ] remove, move example recipes, pins -> proposed name `ilastik/conda-stacks`?

I think the most "natural" place to move the specs/pins files is the repo where ilastik's recipes are stored.  Therefore, I've proposed ilastik/ilastik-build-conda#61, along with some cleanups and updates to the readme file.  I've taken the liberty of removing those files from this branch.  (Hopefully that's okay...)

> - [ ] update `README`

I've removed ilastik-specific text from the README, and copied it into `ilastik-build-conda/README`.

Finally, if you think the above changes are reasonable, and you accept ilastik/ilastik-build-conda#61, then I think this PR can be merged, and you can proceed with the last to-do:

> - [ ] rename repo to `publish-conda-stack`

**Comment by k-dominik** [comment]
Okay @stuarteberg - I think this can be merged now.

**Comment by stuarteberg** [comment]
Quoting myself:

>I've taken the liberty of removing those files from this branch.

...and now I see that I didn't actually push that change.  Thanks for doing it yourself!

**Comment by stuarteberg** [comment]
Updates:

1. Renamed this repo: https://github.com/ilastik/publish-conda-stack
2. Bumped the version
3. Uploaded a new conda package: `conda install -c ilastik-forge publish-conda-stack=0.2.3`

**Comment by k-dominik** [comment]
cool thanks! Upload should not be necessary, btw, if you push the tags (package will be built and uploaded to `ilastik-forge`)

**Comment by stuarteberg** [comment]
oh, nice!

**Pull request merged**
