### PR TITLE
Pin Dependencies

### PR DESCRIPTION
**Pull request by k-dominik**
Striving for more reproducible builds with less pain, this PR tackles the problem of different dependency versions for the different packages we build ourselves. I'm using [build variants](https://conda.io/docs/user-guide/tasks/build-packages/variants.html) here to specify dependency versions. In short, one has to supply a `yaml` file, like in this case `ilastik-pins.yaml` (in the conda-build lingo it is the `conda-build-config.yaml` or `CBC.yaml`). Of course it serves more than the purpose of pinning, but here I only one feature for this PR: In the file specifying key (e.g. package name) value (version) pairs. This kind of superseeds the old `--numpy=..` and `--python=..` arguments to `conda-build`.

All keys specified in the variant file, can be used in the recipes. Conda build has to be invoked with `conda-build -m <variant_file.yaml> ...` in order to take those into account. I made the necessary changes to `build-recipes.py`.

You can see example recipes in https://github.com/k-dominik/ilastik-build-conda/tree/pin-dependencies

If we decide that this is the way to go, we'd have to specify the variables in all the other recipes we build as well.

I just wanted to have you guys' opinions @stuarteberg and @FynnBe

### CODE REVIEW

**Comment by stuarteberg** [comment]
>As I went over all other packages we build, I stumbled over some python-only packages that will also have the `{{CONDA_PY}}` in the version string. Was this done for the sake of consistency with other package names, or is the a different reason I don't see?

Perhaps I'm misunderstanding the question.  You're wondering if the `{{CONDA_PY}}` part can be left out entirely?  Somehow the package name for different versions of python must be distinguished.  Otherwise publishing a package built for e.g. Python 3.7 would overwrite the version built for Python 3.6.  Older versions of conda-build used the convention `0_py36`.  The newer convention uses a hash (which depends on more than just the Python version).  I guess I don't have a strong preference for which convention we use.  If you leave the build string empty entirely, I think conda-build will choose a suitable default.  (It probably won't include the git commit, though, and that can be convenient for forensic analysis sometimes.)

(Packages built for different versions of Python are not interchangeable, even if they are pure-python, because their files are installed to different directories, and also because they are often pre-compiled (via `compileall`) and `.pyc` files are not necessarily compatible between versions).

**Comment by k-dominik** [comment]
Thank you for the clarification @stuarteberg, I wasn't aware that python only packages would be really built. From what I read I thought that something like [ilastik-feature-selection](https://github.com/ilastik/ilastik-feature-selection/tree/master/conda-recipe) in essence a `noarch: python` package which would not need any python build string attached to it? (because installation is basically just placing the files into `site-packages`...)

Having the commit hash in the build string is indeed convenient, since we often build 'non-releases'...

**Comment by stuarteberg** [comment]
>in essence a `noarch: python` package which would not need any python build string attached to it?

OK, after consulting the conda docs again, and inspecting the `.../info/files` for a few `noarch: python` packages, I think you're correct about the meaning of `noarch: python`.  Unless I'm missing something, that means that those packages can't be pre-compiled, since `.pyc` files are not necessarily portable across python versions.  But that's not a big deal, I guess.

My reasoning would apply to `noarch: generic` packages, but I don't think we use that anywhere.

**Comment by k-dominik** [comment]
Thanks.

So after building ilastik for Linux and Mac with this I consider this a working solution. The question to you @stuarteberg, would be whether you want to use the `conda_build_config.py` style of pinning for the flyem recipes as well, or not.

In any case I could then

1) make `build-recipes.py` support both styles. I think if I add a `cbc.yaml` to all our (ilastik) recipes next to the `meta.yaml` it will still work without providing pinnings yourself. Or,
2) I could also open PRs for all your recipes, altering the `meta.yaml`s to use the new style of pinning and add a `flyem-pins.yaml` to this repo.

Or are you not sold to the concept at all, yet?

**Comment by stuarteberg** [comment]
I'm sold!

>make build-recipes.py support both styles.

Don't worry about supporting both styles on my account.  Just support the preferred style.

>I could also open PRs for all your recipes,

Don't worry about that; I'll update them myself.  Just go ahead and merge this branch, and I'll mimic your changes in the flyem recipes when I'm ready.

**Comment by k-dominik** [comment]
thx, playing around with this, a new problem came to surface, that you have pointed out in on of your previous messages:

>  Somehow the package name for different versions of python must be distinguished. Otherwise publishing a package built for e.g. Python 3.7 would overwrite the version built for Python 3.6. Older versions of conda-build used the convention 0_py36. The newer convention uses a hash (which depends on more than just the Python version). 


let's say I update a random dependency via the `ilastik-pins.py`, with the exception of `numpy` or `python` itself, this will _not_ be picked up by `conda-build`, so in fact, the package will not be rebuild. After digging a bit through the conda-build docs and repo, I don't see a way of achieving rebuilds upon dependency change if we keep the current custom build string.

**Comment by stuarteberg** [comment]
Yeah, that's why the default build string provided by conda-build now uses a hash, which it computes from the contents of the `requirements` (and other stuff).

I guess our options are:
- Remove our custom build string and let conda-build pick a default

OR

- Use a custom string that incorporates `{{PKG_HASH}}`, maybe something like this:
    `{{PKG_BUILDNUM}}_h{{PKG_HASH}}_g{{GIT_FULL_HASH[:7]}}`

For my own packages, I'll probably try the custom string, but I do not have a strong opinion for the packages that we share.  (The conda-build developers recommend against customizing the build string, because people can screw it up if they don't know what we're doing.  But I like to live dangerously.)

**Comment by k-dominik** [comment]
Aight, we'll ride the dangerous trail with you ;) while being a bit redundant I fixed build strings to

* `py{{CONDA_PY}}np{{CONDA_NPY}}_{{PKG_BUILDNUM}}_h{{PKG_HASH}}_g{{GIT_FULL_HASH[:7]}}`

**Pull request merged**
